apiVersion: v1
kind: Service
metadata:
  name: my-app-service

spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008

  selector:
    app: my-app
    type: front-end
