apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-Daemon
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
        - name: monitoring-agent
          image: <your-docker-image-registry>/<your-docker-image-name>:latest
