apiVersion: v1
kind: Service
metadata:
  name: my-app-service

spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30000 # Range 30000-32767
  selector:
    app: my-app
    type: front-end
